name: CI

on:
  push:
    branches: [develop-renovate]
  pull_request:
    branches: [develop-renovate]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: CultureHQ/actions-yarn@v1.0.1
        with:
          node-version: 14
      - run: yarn
      - run: yarn build
      - run: yarn version --patch
      - uses: ludeeus/action-push@0.0.1
